# g++ -o show_ip4_all_exe show_ip4_all.cpp
all: show_ip4_all_exe show_ip4_exe
show_ip4_all_exe: show_ip4_all.cpp
	g++ -o show_ip4_all_exe show_ip4_all.cpp

show_ip4_exe: show_ip4.cpp
	g++ -o show_ip4_exe show_ip4.cpp